// <auto-generated />
using DrinksShop.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrinksShop.Api.Migrations
{
    [DbContext(typeof(DrinksShopDbContext))]
    [Migration("20221214172012_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrinksShopOnline.Api.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("DrinksShopOnline.Api.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("DrinksShopOnline.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "Имеет истонченный вкус, нравится детям",
                            ImageURL = "/Images/Drinks/KlavaCoca.jpg",
                            Name = "Клава Кока",
                            Price = 40m,
                            Qty = 50,
                            Volume = 1.25
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Виски, рекомендован самим Тарасом Григорьевичем. Отлично подойдет на большую компанию, 40%",
                            ImageURL = "/Images/Drinks/JekaJihar.jpg",
                            Name = "Жека Жихарь",
                            Price = 500m,
                            Qty = 30,
                            Volume = 0.69999999999999996
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Укрпеляет здоровье, за счет большого количества витамина С",
                            ImageURL = "/Images/Drinks/Ablepiha.jpg",
                            Name = "АБЛЕПИХА",
                            Price = 34m,
                            Qty = 250,
                            Volume = 0.5
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Идеально подходит для продавцов возле школы, 8.5%",
                            ImageURL = "/Images/Drinks/Vika.jpg",
                            Name = "Пьяная Вика",
                            Price = 46m,
                            Qty = 950,
                            Volume = 0.5
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Лучший напиток под пиццу из <<Буфета>>, лимончик чувствуется",
                            ImageURL = "/Images/Drinks/Svejiy.jpg",
                            Name = "СВЕЖИЙ",
                            Price = 35m,
                            Qty = 150,
                            Volume = 0.5
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "На большую компанию, по началу неплохо, но, все же, лучше не покупать более 5 раз, 37.5%",
                            ImageURL = "/Images/Drinks/NicolayMorgan.jpg",
                            Name = "Николай Морган",
                            Price = 205m,
                            Qty = 40,
                            Volume = 0.69999999999999996
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Лучше не показывать девочкам, подойдет для посиделок в общаге, 38%",
                            ImageURL = "/Images/Drinks/MahaMary.jpg",
                            Name = "MAHAMARY",
                            Price = 140m,
                            Qty = 60,
                            Volume = 0.69999999999999996
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Более дорогая водка, для тех, кто хочет опробовать себя в роли статусного человека, 40%",
                            ImageURL = "/Images/Drinks/JekaBounty.jpg",
                            Name = "Жека Баунти",
                            Price = 340m,
                            Qty = 20,
                            Volume = 0.69999999999999996
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Коктейль-отвертка, но с изюминкой. Подойдет для девушек и летнего отдыха, для пляжей, 7%",
                            ImageURL = "/Images/Drinks/Katerok.jpg",
                            Name = "Катерок <<Sexx в гармошке>>",
                            Price = 38m,
                            Qty = 220,
                            Volume = 0.5
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Престижный крепкий алкоголь, желательно иметь всегда, схож на сироп от кашля, 35%",
                            ImageURL = "/Images/Drinks/Panch.jpg",
                            Name = "Панченёнок",
                            Price = 400m,
                            Qty = 305,
                            Volume = 0.5
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Холодный чай с достаточно приятным вкусом. Зачастую нравится девушкам",
                            ImageURL = "/Images/Drinks/Kettle.jpg",
                            Name = "Чайник",
                            Price = 38m,
                            Qty = 75,
                            Volume = 0.5
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Альтернатива свежему, все так же хорош под пиццу",
                            ImageURL = "/Images/Drinks/Oops.jpg",
                            Name = "УПС!",
                            Price = 38m,
                            Qty = 70,
                            Volume = 0.5
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Энергетический напиток за 2 гривны. Не рекомендуется к употреблению до 18 лет",
                            ImageURL = "/Images/Drinks/Black.jpg",
                            Name = "ЧЕРНЫЙ",
                            Price = 10m,
                            Qty = 100,
                            Volume = 0.5
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Субисидия. Народный, 3х литровый стандарт для людей на мели",
                            ImageURL = "/Images/Drinks/Maloi.jpg",
                            Name = "Малой",
                            Price = 7m,
                            Qty = 25,
                            Volume = 3.0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Description = "Крепкий стандарт для людей, у которых нечувствителен язык, 9%",
                            ImageURL = "/Images/Drinks/Petushara.jpg",
                            Name = "Петушара",
                            Price = 30m,
                            Qty = 30,
                            Volume = 1.0
                        });
                });

            modelBuilder.Entity("DrinksShopOnline.Api.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Алкогольный напиток"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Безалкогольный напиток"
                        });
                });

            modelBuilder.Entity("DrinksShopOnline.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserName = "Kyrylo"
                        },
                        new
                        {
                            Id = 2,
                            UserName = "Dmytro"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
